config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  resources :posts do
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'post' }
    resources :comments do
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'comment' }
    end
  end
  resources :profiles do
    resource :followers
    resources :posts
    member do
      get 'my_posts'
    end
  end
  resources :subscriptions do
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'post' }
    resources :comments do
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'comment' }
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "main#home"
  
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
    validates :username, uniqueness: true, on: :create
    has_one_attached :avatar
    has_many :post
     
    has_many :followed_relationships, class_name: 'Follower', foreign_key: 'follower_id'
    has_many :following, through: :followed_relationships, source: :followed
  
    has_many :follower_relationships, class_name: 'Follower', foreign_key: 'followed_id'
    has_many :followers, through: :follower_relationships, source: :follower
  
    def follow(profile)
      followed_relationships.create(followed: profile)
    end
  
    def unfollow(profile)
      followed_relationships.where(followed: profile).destroy_all
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
  before_action :set_profile, only: [:edit, :update]
before_action :authorize_user!, only: [:edit, :update]
  def new
    @profile = current_user.build_profile
  end
    
  def edit
    # Отобразить форму для редактирования профиля
  end

  def show
    @profile = Profile.find(params[:id])
    @posts = @profile.post
    end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to edit_profile_path(@profile), notice: 'Профиль успешно создан.'
    else
      render :new
    end
  end



  def update
    if @profile.update(profile_params)
      redirect_to profile_path(@profile), notice: 'Профиль успешно обновлен.'
    else
      render :edit
    end
  end

  private

  def set_profile
    @profile = current_user.profile || current_user.create_profile
  end

  def profile_params
    params.require(:profile).permit(:username, :description, :avatar)
  end

  def my_posts
    @profile = current_user.profile
    @posts = @profile.posts
    render :show
  end

  def authorize_user!
    unless @profile == current_user.profile
      redirect_to @profile, alert: 'You are not authorized to edit this profile.'
    end
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<h2>Редактировать профиль</h2>

<%= form_for(@profile, url: profile_path(@profile), method: :patch) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "ошибка") %> запрещают сохранение профиля:</h2>
      <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
<div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
    <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit "Сохранить" %>
  </div>
<% end %>

app/views/profiles/new.html.erb
<h2>Создать профиль</h2>

<%= form_with(model: @profile, local: true) do |form| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "ошибка") %> запрещают сохранение профиля:</h2>
      <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, required: true %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit "Создать профиль" %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div class="card">
<h1><%= @profile.username%></h1>
<h4><%= @profile.user.email %></h4>
<% if @profile.avatar.attached? %>
    <%= image_tag(@profile.avatar, class:"img-thumbnail rounded float-end border border-danger")%>
    
  <% else %>
    <span>Нет аватара</span>
  <% end %>
<h4><%= @profile.description%></h4>

</div>
<% if @profile.user == current_user %>
  <%= link_to 'Изменить профиль', edit_profile_path(@profile) %>
<% end %>


<% if user_signed_in? && current_user.profile != @profile %>
  <% if current_user.profile.following.include?(@profile) %>
    <%= button_to 'Отписаться', profile_followers_path(@profile), method: :delete, class: 'btn btn-secondary' %>
  <% else %>
    <%= button_to 'Подписаться', profile_followers_path(@profile), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<% if user_signed_in? %>
  <%= link_to "Подписчики  #{ @profile.followers.count}" , profile_followers_path(@profile) %>
<% end %>
<% if user_signed_in? %>
  <%= link_to "Подписки  #{ @profile.following.count}" , profile_followers_path(@profile) %>
<% end %>


<% @posts.reverse.each_with_index do |post, i_post| %>




<div class="card">



<div class="card-body">
  <div>
 
   <%= link_to post.profile.username, profile_path(post.profile), class: "btn btn-primary" %>
    <h3 class="card-title"><%= link_to post.description, post %></h3>
    
    <div id="carouselExample<%=i_post%>" class="carousel slide ">
    <div class="carousel-inner">



        <% post.images.each_with_index do |image, i | %>
        <% if i ==0 %>
          <div class="carousel-item active">
        <%else%>
        <div class="carousel-item">
        <% end %>
          <%= image_tag image ,class:"d-block w-100"%>
          </div>
        <% end %>
   
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample<%=i_post%>" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample<%=i_post%>" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>

    </div>

  </div>
  <% like = post.like.find_by(profile: current_user.profile) %>

<div class="btn-group" role="group">
  <!-- Кнопка для лайка -->
  <%= form_with(url: post_likes_path(post), method: :post, local: true) do |form| %>
    <%= hidden_field_tag :likeable_id, post.id %>
    <%= hidden_field_tag :likeable_type, 'Post' %>
    <%= hidden_field_tag :like_type, 1 %> <!-- Устанавливаем лайк -->

    <%= form.submit '👍🏻', class: like.present? && like.like_type == 1 ? 'active-like btn btn-success'  : "inactive-like  btn btn-outline-success" %>
    <span><%= post.like.where(like_type: 1).count %></span> <!-- Подсчет лайков -->
  <% end %>

  <!-- Кнопка для дизлайка -->
  <%= form_with(url: post_likes_path(post), method: :post, local: true) do |form| %>
    <%= hidden_field_tag :likeable_id, post.id %>
    <%= hidden_field_tag :likeable_type, 'Post' %>
    <%= hidden_field_tag :like_type, -1 %> <!-- Устанавливаем дизлайк -->

    <%= form.submit '👎🏻', class: like.present? && like.like_type == -1 ? 'active-dislike btn btn-danger' : 'inactive-dislike btn btn-outline-danger'%>
    <span><%= post.like.where(like_type: -1).count %></span> <!-- Подсчет дизлайков -->
  <% end %>
</div>
</div>
  <%= link_to 'Изменить пост', edit_post_path(post) %>
</div>
<% end %>