config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  resources :posts do
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'post' }
    resources :comments do
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'comment' }
    end
  end
  resources :profiles do
    resource :followers
    resources :posts
    member do
      get 'my_posts'
    end
  end
  resources :subscriptions do
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'post' }
    resources :comments do
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'comment' }
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "main#home"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :profile
  belongs_to :post
  has_many_attached :images
  has_many :like, as: :likeable, dependent: :destroy


  def deleted?
    deleted_at.present?
  end

  def soft_delete
    update(deleted_at: Time.current)
  end

  def restore
    update(deleted_at: nil)
  end

  scope :active, -> { where(deleted_at: nil) }
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :follower, class_name: 'Profile'
  belongs_to :followed, class_name: 'Profile'

  validates :follower_id, uniqueness: { scope: :followed_id }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :profile
  belongs_to :likeable, polymorphic: true

  validates :like_type, inclusion: { in: [1, -1] } 
  validates :profile_id, uniqueness: { scope: [:likeable_type, :likeable_id] } 
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :profile
  has_many_attached :images
  has_many :comment
  has_many :like, as: :likeable, dependent: :destroy
  
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
    validates :username, uniqueness: true, on: :create
    has_one_attached :avatar
    has_many :post
     
    has_many :followed_relationships, class_name: 'Follower', foreign_key: 'follower_id'
    has_many :following, through: :followed_relationships, source: :followed
  
    has_many :follower_relationships, class_name: 'Follower', foreign_key: 'followed_id'
    has_many :followers, through: :follower_relationships, source: :follower
  
    def follow(profile)
      followed_relationships.create(followed: profile)
    end
  
    def unfollow(profile)
      followed_relationships.where(followed: profile).destroy_all
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one :profile, dependent: :destroy
         after_create :create_profile
  accepts_nested_attributes_for :profile


  def create_profile
    base_username = email.split('@').first
    unique_username = generate_unique_username(base_username)
    
    build_profile(username: unique_username)
    save
  end

  private

  def generate_unique_username(base_username)
    username = base_username
    counter = 1

    # Проверяем, существует ли уже такой username
    while Profile.exists?(username: username)
      username = "#{base_username}#{counter}"
      counter += 1
    end

    username
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!   
    before_action :set_profile
    before_action :set_comment, only: [:destroy]

    def index
        @posts = Post.Comment.all
      end

    def create
        @post = Post.find(params[:post_id])

        @comment = @post.comment.build(comment_params)
        @comment.profile = current_user.profile 
        if @comment.save
          redirect_to @post, notice: 'Comment was successfully created.'
        else
          render :new
        end
      end
      def destroy
        if @comment.profile == current_user.profile
          @comment.soft_delete # Используем soft_delete, чтобы пометить комментарий как удаленный
          
        else
          # Если текущий пользователь не является автором комментария, перенаправляем с ошибкой
          redirect_to @post, alert: 'You are not authorized to delete this comment.'
        end
      end
    private
    
    def set_profile
      if current_user.profile.nil?
        redirect_to new_profile_path, alert: 'You need to create a profile first.'
      else
        @profile = current_user.profile
      end
    end
    
  
    def comment_params
      params.require(:comment).permit(:title, images: [])
    end

    def set_comment
      @post = Post.find(params[:post_id])
      @comment = @post.comment.find(params[:id])
    end
  end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_likeable
    
    def create
      like = @likeable.like.find_or_initialize_by(profile: current_user.profile)
  
      # Если тип лайка совпадает, удаляем лайк (то есть снимаем его)
      if like.persisted? && like.like_type == params[:like_type].to_i
        like.destroy
      else
        # Иначе обновляем или создаем новый лайк/дизлайк
        like.update(like_type: params[:like_type].to_i)
      end
  
      redirect_back(fallback_location: root_path)
    end
  
    private
  
    def set_likeable
      @likeable = if params[:post_id]
                    Post.find(params[:post_id])
                  elsif params[:comment_id]
                    Comment.find(params[:comment_id])
                  end
    end
  end
  

app/controllers/main_controller.rb
class MainController < ApplicationController
    def home
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!   
    before_action :set_profile
    before_action :authorize_user!, only: [:edit, :update]
    def index
        @posts = Post.all
      end
      def edit
        
        # Отобразить форму для редактирования профиля
      end
    def show
        @post = Post.find(params[:id])
        @comments = @post.comment
        @comment = @post.comment.build
        @likes_count = @post.like.where(like_type: 1).count
        @dislikes_count = @post.like.where(like_type: -1).count
      end
    def new
        @post = @profile.post.build
      end
    
      def create
        @post = @profile.post.build(post_params)
        if @post.save
          redirect_to @profile, notice: 'Post was successfully created.'
        else
          render :new
        end
      end


      def update
         @post = Post.find(params[:id])
        if @post.update(post_params)
          redirect_to @post, notice: 'Post was successfully updated.'
        else
          render :edit
        end

      end


      private
    def set_post
    @post = Post.find(params[:id])
    end
      def set_profile
        if current_user.profile.nil?
          redirect_to new_profile_path, alert: 'You need to create a profile first.'
        else
          @profile = current_user.profile
        end
      end
      
    
      def post_params
        params.require(:post).permit(:description, images: [])
      end

      def authorize_user!
        set_post
        unless @post.profile == current_user.profile
          redirect_to @post, alert: 'You are not authorized to edit this post.'
        end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Social Saw" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application",  media: 'all',"data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>  
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <div class="container">
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary">
<div class="container-fluid">
  <%= link_to 'Главная', posts_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
      <li class="nav-item">
      
        <%= link_to 'Посты', posts_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
       <% if current_user.profile %>
        <li class="nav-item">
          <%= link_to 'Подписки',  subscription_path(current_user.profile), class: 'nav-link' %>
        </li> 
      <li class="nav-item">
      
          <%= link_to 'Профиль', profile_path(current_user.profile), class: 'nav-link bi bi-person-circle' %>
          
        </li>
        
        <li class="nav-item">
          <%= link_to 'Создать пост', new_post_path, class: 'nav-link' %>
        </li>
       
       <% else%>
         <li class="nav-item">
        <%= link_to 'Создать профиль', new_profile_path,  class: 'nav-link'%>
        </li> 
      <% end %>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
  </div>
</nav>