config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  resources :posts do
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'post' }
    resources :comments do
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'comment' }
    end
  end
  resources :profiles do
    resource :followers
    resources :posts
    member do
      get 'my_posts'
    end
  end
  resources :subscriptions do
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'post' }
    resources :comments do
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'comment' }
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "main#home"
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :profile
  has_many_attached :images
  has_many :comment
  has_many :like, as: :likeable, dependent: :destroy
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!   
    before_action :set_profile
    before_action :authorize_user!, only: [:edit, :update]
    def index
        @posts = Post.all
      end
      def edit
        
        # Отобразить форму для редактирования профиля
      end
    def show
        @post = Post.find(params[:id])
        @comments = @post.comment
        @comment = @post.comment.build
        @likes_count = @post.like.where(like_type: 1).count
        @dislikes_count = @post.like.where(like_type: -1).count
      end
    def new
        @post = @profile.post.build
      end
    
      def create
        @post = @profile.post.build(post_params)
        if @post.save
          redirect_to @profile, notice: 'Post was successfully created.'
        else
          render :new
        end
      end


      def update
         @post = Post.find(params[:id])
        if @post.update(post_params)
          redirect_to @post, notice: 'Post was successfully updated.'
        else
          render :edit
        end

      end


      private
    def set_post
    @post = Post.find(params[:id])
    end
      def set_profile
        if current_user.profile.nil?
          redirect_to new_profile_path, alert: 'You need to create a profile first.'
        else
          @profile = current_user.profile
        end
      end
      
    
      def post_params
        params.require(:post).permit(:description, images: [])
      end

      def authorize_user!
        set_post
        unless @post.profile == current_user.profile
          redirect_to @post, alert: 'You are not authorized to edit this post.'
        end
      end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<%= form_for(@post, url: post_path(@post), method: :patch) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
  <div class="field ">
    <%= form.label :description %>
    <%= form.text_area :description , class: "form-floating"%>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images , multiple: true, class: "input-group-text" %>
  </div>

  <div class="actions">
    <%= form.submit "Обновить", class:"btn btn-primary" %>
  </div>

</div>


<% end %>

app/views/posts/index.html.erb
<h1>Общая лента</h1>

<% @posts.reverse.each_with_index do |post, i_post| %>




<div class="card">



<div class="card-body">
  <div>
 
   <%= link_to post.profile.username, profile_path(post.profile), class: "btn btn-primary" %>
    <h3 class="card-title"><%= link_to post.description, post %></h3>
    
    <div id="carouselExample<%=i_post%>" class="carousel slide ">
    <div class="carousel-inner">



        <% post.images.each_with_index do |image, i | %>
        <% if i ==0 %>
          <div class="carousel-item active">
        <%else%>
        <div class="carousel-item">
        <% end %>
          <%= image_tag image ,class:"d-block w-100"%>
          </div>
        <% end %>
   
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample<%=i_post%>" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample<%=i_post%>" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>

    </div>

  </div>
  <% like = post.like.find_by(profile: current_user.profile) %>

<div class="btn-group" role="group">
  <!-- Кнопка для лайка -->
  <%= form_with(url: post_likes_path(post), method: :post, local: true) do |form| %>
    <%= hidden_field_tag :likeable_id, post.id %>
    <%= hidden_field_tag :likeable_type, 'Post' %>
    <%= hidden_field_tag :like_type, 1 %> <!-- Устанавливаем лайк -->

    <%= form.submit '👍🏻', class: like.present? && like.like_type == 1 ? 'active-like btn btn-success'  : "inactive-like  btn btn-outline-success" %>
    <span><%= post.like.where(like_type: 1).count %></span> <!-- Подсчет лайков -->
  <% end %>

  <!-- Кнопка для дизлайка -->
  <%= form_with(url: post_likes_path(post), method: :post, local: true) do |form| %>
    <%= hidden_field_tag :likeable_id, post.id %>
    <%= hidden_field_tag :likeable_type, 'Post' %>
    <%= hidden_field_tag :like_type, -1 %> <!-- Устанавливаем дизлайк -->

    <%= form.submit '👎🏻', class: like.present? && like.like_type == -1 ? 'active-dislike btn btn-danger' : 'inactive-dislike btn btn-outline-danger'%>
    <span><%= post.like.where(like_type: -1).count %></span> <!-- Подсчет дизлайков -->
  <% end %>
</div>
</div>
</div>
<% end %>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="container">
  <div class="field ">
    <%= form.label :description %>
    <%= form.text_area :description , class: "form-floating"%>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images , multiple: true, class: "input-group-text" %>
  </div>

  <div class="actions">
    <%= form.submit "Создать", class:"btn btn-primary" %>
  </div>

</div>
<% end %>

app/views/posts/show.html.erb
<h3><%= link_to @post.profile.username, profile_path(@post.profile) %></h3>
<h1><%= @post.description %></h1>

<div id="carouselExample" class="carousel slide ">
    <div class="carousel-inner">



        <% @post.images.each_with_index do |image, i | %>
        <% if i ==0 %>
          <div class="carousel-item active">
        <%else%>
        <div class="carousel-item">
        <% end %>
          <%= image_tag image ,class:"d-block w-100"%>
          </div>
        <% end %>
   
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>

    </div>

<% if @post.profile.user == current_user %>
  <%= link_to 'Изменить пост', edit_post_path(@post), class: "btn btn-warning "%>
<% end %>



<% like = @post.like.find_by(profile: current_user.profile) %>

<div class="btn-group" role="group">
  
  <%= form_with(url: post_likes_path(@post), method: :post, local: true) do |form| %>
    <%= hidden_field_tag :likeable_id, @post.id %>
    <%= hidden_field_tag :likeable_type, 'Post' %>
    <%= hidden_field_tag :like_type, 1 %> 

    <%= form.submit '👍🏻', class: like.present? && like.like_type == 1 ? 'active-like btn btn-success'  : "inactive-like  btn btn-outline-success" %>
    <span><%= @post.like.where(like_type: 1).count %></span> 
  <% end %>

 
  <%= form_with(url: post_likes_path(@post), method: :post, local: true) do |form| %>
    <%= hidden_field_tag :likeable_id, @post.id %>
    <%= hidden_field_tag :likeable_type, 'Post' %>
    <%= hidden_field_tag :like_type, -1 %> 

    <%= form.submit '👎🏻', class: like.present? && like.like_type == -1 ? 'active-dislike btn btn-danger' : 'inactive-dislike btn btn-outline-danger' %>
    <span><%= @post.like.where(like_type: -1).count %></span> 
  <% end %>
</div>











<% @comments.active.reverse.each_with_index do |comment,i_post| %>

<div class="card">



    <div class="card-body">
  
    <% if comment.profile.present? %>
      <%= link_to comment.profile.username, profile_path(comment.profile) , class: "card-title"%>
  <%= form_with(url: post_comment_path(@post, comment), method: :delete, remote: true, data: { confirm: 'Are you sure?' }) do |form| %>
  <%= form.submit 'Delete', class: 'delete-button btn btn-sm btn-outline-danger' %>
  <% end %>


    <% else %>
      <p>Аноним</p> 
    <% end %>
 
   <p><%= comment.title %></p> 
    <div id="carouselExample<%=i_post%>" class="carousel slide ">
    <div class="carousel-inner">

  <% comment.images.each_with_index do |image, i | %>
        <% if i ==0 %>
          <div class="carousel-item active">
        <%else%>
        <div class="carousel-item">
        <% end %>
          <%= image_tag image ,class:"d-block w-100"%>
          </div>
        <% end %>
   
      </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample<%=i_post%>" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample<%=i_post%>" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>
</div>

<% end %>

<%= form_with(model: [@post, @comment], local: true) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit "Отправить" ,class:"btn btn-primary"%>
  </div>



<% end %>